name: Check Issue for Code Formatting
on:
  issues:
    types:
      - opened

env:
  GH_TOKEN: ${{ secrets.DUCKDBLABS_BOT_TOKEN }}

jobs:
  check_code_formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  
      - name: Check issue for code formatting
        run: |
          echo "${{ github.event.issue.body }}" 
          if ! echo "${{ github.event.issue.body }}" | python3 scripts/check-issue-for-code-formatting.py; then
              gh issue comment ${{ github.event.issue.number }} --body-file .github/workflows/code-formatting-warning.md
          fi
